### Notes
#
# - using the 'build' config instead of 'image' allows to build the platform with just 'docker-compose build'
# - SYS_PTRACE capability is needed to allow tghe containers to read /proc/$PID, which is needed by init scripts
#
# The docker-compose 'service' name corresponds to the top-level yml keys, whereas the container name is used in most
# 'docker' commands.
# Keeping a separate container name for each project allows to run many container platforms in parallel
version: '2'
services:
    front1:
        image: crevillo/nginx_${DOCKER_PHP_VERSION}
        hostname: ${DOCKER_PROJECT_NAME}_dev
        container_name: front1
        privileged: true
        volumes:
            - ./logs/cli:/var/log/php
            # files in /tmp/cron.d get managed by bootstrap.sh
            - ./config/cli/cron.d:/tmp/cron.d
            - ~/.gitconfig:/home/site/.gitconfig
            - ~/.ssh/config:/home/site/.ssh/config
            - "$SSH_AUTH_SOCK:/ssh-agent"
            - "./config/cli/php5/custom_vars.ini:$DOCKER_PHP_CONF_PATH/cli/conf.d/custom_vars.ini"
            - "./config/cli/php5/timezone.ini:$DOCKER_PHP_CONF_PATH/cli/conf.d/timezone.ini"
            - "$DOCKER_WWW_ROOT:$DOCKER_WWW_DEST"
            - "$DOCKER_STORAGE_LOCAL_PATH:$DOCKER_STORAGE_MOUNT_POINT"
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
        env_file:
            - docker-compose.env
            - docker-compose.env.local
        cap_add:
            - SYS_PTRACE
